---
gentl_producer_path = "/opt/pylon/lib/gentlproducer/gtl/ProducerGEV.cti"
ace2_serial_number_windmill = "24595666"
ace2_serial_number_vessel = "0000000"
H = 720
W = 1280
D = 3
image-format = "BayerBG8"

CAM_GRABBER_PROCESS_SILENT = False
NO_CAM_COUNTER_MAX = 20
FPS_PRINT_INTERVAL = 1 # [s]
...


---
# 


...